# This pipeline runs for every commit/merge/etc.
# It is intended to be basic and quick sanity-checking
kind: pipeline
type: docker
name: Verify

steps:
  - name: Node Install
    image: node:12-slim
    commands:
      - npm ci
    volumes:
      - name: npm-cache
        path: /root/.npm
  - name: Node Lint
    image: node:12-slim
    commands:
      - npm run lint
    depends_on:
      - Node Install
  - name: Node Audit
    image: node:12-slim
    commands:
      - npm audit --audit-level=moderate
    depends_on:
      - Node Install

  - name: Server Test
    image: golang:1.15
    volumes:
    - name: go-cache
      path: /go
    commands:
      - go test -race ./...
      - go vet $(go list ./... | grep -v "vendor")
  - name: Server Static Check
    image: golang:1.15
    volumes:
    - name: go-cache
      path: /go
    commands:
      - go run honnef.co/go/tools/cmd/staticcheck ./...
    depends_on:
      - Server Test

  - name: Integration Test Build
    image: golang:1.15
    volumes:
    - name: go-cache
      path: /go
    commands:
      - go build -o simple-auth-server simple-auth/cmd/server
    depends_on:
      - Server Test

  - name: Integration Tests
    image: node:12-buster
    commands:
      - ./tests/quicktest.sh --nobuild
    depends_on:
      - Integration Test Build
    

volumes:
  - name: docker-socket
    host:
      path: /var/run/docker.sock
  - name: go-cache
    host:
      path: /var/ci/cache/simple-auth-go
  - name: npm-cache
    host:
      path: /var/ci/cache/simple-auth-npm

---
kind: pipeline
type: docker
name: Docker Build

depends_on:
  - Verify
trigger:
  branch: ['master']

steps:
  - name: Docker Build
    image: docker:19
    volumes:
    - name: docker-socket
      path: /var/run/docker.sock
    commands:
      - docker build -t ${DRONE_REPO_NAME}-${DRONE_BUILD_NUMBER} .

  - name: Docker Push
    image: docker:19
    volumes:
    - name: docker-socket
      path: /var/run/docker.sock
    environment:
      DOCKER_REGISTRY_USERNAME:
        from_secret: rdh_user
      DOCKER_REGISTRY_PASSWORD:
        from_secret: rdh_pass
    commands:
      - docker login -u "$DOCKER_REGISTRY_USERNAME" -p "$DOCKER_REGISTRY_PASSWORD"
      - docker tag ${DRONE_REPO_NAME}-${DRONE_BUILD_NUMBER} zix99/simple-auth:latest
      - docker tag ${DRONE_REPO_NAME}-${DRONE_BUILD_NUMBER} zix99/simple-auth:${DRONE_BUILD_NUMBER}
      - docker tag ${DRONE_REPO_NAME}-${DRONE_BUILD_NUMBER} "zix99/simple-auth:${DRONE_TAG}"
      - docker push zix99/simple-auth
    when:
      event: ['tag']
    depends_on:
      - Docker Build

volumes:
  - name: docker-socket
    host:
      path: /var/run/docker.sock

---

kind: pipeline
type: docker
name: Binary Build

depends_on:
  - Verify
trigger:
  branch:
    - master

steps:
  - name: Node Install
    image: node:12-slim
    commands:
      - npm ci
    volumes:
      - name: npm-cache
        path: /root/.npm

  - name: Node Dist
    image: node:12-slim
    commands:
      - npm run build
    depends_on:
      - Node Install

  - name: Server Generate
    image: golang:1.15
    volumes:
    - name: go-cache
      path: /go
    commands:
      - go generate ./...
      - go run github.com/swaggo/swag/cmd/swag init -o pkg/swagdocs -g pkg/routes/api/api.go
      - mkdir -p bin/
    depends_on:
      - Node Dist

  - name: Server Build (Linux64)
    image: golang:1.15
    volumes:
    - name: go-cache
      path: /go
    environment:
      GOOS: linux
      GOARCH: amd64
    commands:
      - go build -tags box,swagger,prometheus -o bin/simple-auth-server simple-auth/cmd/server
    depends_on:
      - Server Generate

  - name: Release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_release_apikey
      files: bin/*
      checksum:
        - sha1
    depends_on:
      - Server Build (Linux64)
    when:
      event: ['tag']

volumes:
  - name: go-cache
    host:
      path: /var/ci/cache/simple-auth-go
  - name: npm-cache
    host:
      path: /var/ci/cache/simple-auth-npm

---
kind: pipeline
type: docker
name: Documentation

trigger:
  event:
    - promote
  target:
    - docs

steps:
  - name: Node Install
    image: node:12-slim
    commands:
      - cd docs && npm ci
    volumes:
      - name: npm-cache
        path: /root/.npm
  - name: Server Generate
    image: golang:1.15
    volumes:
    - name: go-cache
      path: /go
    commands:
      - go run github.com/swaggo/swag/cmd/swag init -o pkg/swagdocs -g pkg/routes/api/api.go
  - name: Docs Build
    image: node:12-slim
    commands:
      - cd docs && npm run build
  - name: Docs Test
    image: node:12
    commands:
      - cd docs && npm run test
  - name: Deploy
    image: node:12-slim
    environment:
      SURGE_LOGIN:
        from_secret: surge_login
      SURGE_TOKEN:
        from_secret: surge_token
    commands:
      - cd docs && npm run deploy

volumes:
  - name: npm-cache
    host:
      path: /var/ci/cache/simple-auth-npm
  - name: go-cache
    host:
      path: /var/ci/cache/simple-auth-go

---

kind: pipeline
type: docker
name: Sync

trigger:
  branch:
  - master

depends_on:
  - Verify

steps:
  - name: Push To Github
    image: alpine/git
    environment:
      GIT_KEY:
        from_secret: sshkey_github
    commands:
      - mkdir -p /root/.ssh && echo "$GIT_KEY" > /root/.ssh/id_rsa && chown 400 /root/.ssh/id_rsa
      - ssh-keyscan github.com >> /root/.ssh/known_hosts
      - git remote add mirror git@github.com:zix99/simple-auth.git
      - git push mirror --force

