kind: pipeline
name: default

steps:
  - name: Node Install
    image: node:12-slim
    commands:
      - npm ci
    volumes:
      - name: npm-cache
        path: /root/.npm
  - name: Node Lint
    image: node:12-slim
    commands:
      - npm run lint
    depends_on:
      - Node Install
  - name: Node Audit
    image: node:12-slim
    commands:
      - npm audit --audit-level=moderate
    depends_on:
      - Node Install
  - name: Node Dist
    image: node:12-slim
    commands:
      - npm run build
    depends_on:
      - Node Install
      - Node Lint # Cause why bother if failed

  - name: Server Generate
    image: golang:1.14
    volumes:
    - name: go-cache
      path: /go
    commands:
      - go generate ./...
    when:
      branch: ['master']

  - name: Server Test
    image: golang:1.14
    volumes:
    - name: go-cache
      path: /go
    commands:
      - go test -race ./...
      - go vet $(go list ./... | grep -v "vendor")
      - go run honnef.co/go/tools/cmd/staticcheck ./...
    depends_on:
      - Server Generate
  - name: Server Build
    image: golang:1.14
    volumes:
    - name: go-cache
      path: /go
    commands:
      - go build -tags box -o simple-auth-server simple-auth/cmd/server
    depends_on:
      - Server Generate
      - Node Dist
  - name: CLI Build
    image: golang:1.14
    volumes:
    - name: go-cache
      path: /go
    commands:
      - go build -o simple-auth-cli simple-auth/cmd/cli
    depends_on:
      - Server Generate

  - name: Integration Tests
    image: node:12-buster
    commands:
      - ./tests/quicktest.sh --nobuild
    depends_on:
      - Server Build

  - name: Docker Build
    image: docker:19
    volumes:
    - name: docker-socket
      path: /var/run/docker.sock
    commands:
      - docker build -t ${DRONE_REPO_NAME} -f Dockerfile.drone .
    when:
      branch: ['master']
    depends_on:
      - Server Build
      - CLI Build

volumes:
  - name: docker-socket
    host:
      path: /var/run/docker.sock
  - name: go-cache
    host:
      path: /var/ci/cache/simple-auth-go
  - name: npm-cache
    host:
      path: /var/ci/cache/simple-auth-npm
