kind: pipeline
name: default

steps:
  - name: Install
    image: node:12-slim
    commands:
      - npm ci
    volumes:
      - name: npm-cache
        path: /root/.npm
  - name: Lint
    image: node:12-slim
    commands:
      - npm run lint
  - name: Audit
    image: node:12-slim
    commands:
      - npm audit --audit-level=moderate
  - name: JS Dist
    image: node:12-slim
    commands:
      - npm run build

  - name: Server Generate
    image: golang:1.14
    volumes:
    - name: go-cache
      path: /go
    commands:
      - go generate ./...
    when:
      branch: ['master']

  - name: Server Test
    image: golang:1.14
    volumes:
    - name: go-cache
      path: /go
    commands:
      - go test -race -cover ./...
      - go vet $(go list ./... | grep -v "vendor")
      - go run honnef.co/go/tools/cmd/staticcheck ./...
  - name: Server Build
    image: golang:1.14
    volumes:
    - name: go-cache
      path: /go
    commands:
      - go build -tags box -o simple-auth-server simple-auth/cmd/server
  - name: CLI Build
    image: golang:1.14
    volumes:
    - name: go-cache
      path: /go
    commands:
      - go build -o simple-auth-cli simple-auth/cmd/cli

  - name: Integration Tests
    image: node:12
    commands:
      - ./tests/quicktest.sh --nobuild

  - name: Docker Build
    image: docker:19
    volumes:
    - name: docker-socket
      path: /var/run/docker.sock
    commands:
      - docker build -t ${DRONE_REPO_NAME} -f Dockerfile.drone .
    when:
      branch: ['master']

volumes:
  - name: docker-socket
    host:
      path: /var/run/docker.sock
  - name: go-cache
    host:
      path: /var/ci/cache/simple-auth-go
  - name: npm-cache
    host:
      path: /var/ci/cache/simple-auth-npm
