kind: pipeline
name: default

steps:
  - name: Node Install
    image: node:12-slim
    commands:
      - npm ci
    volumes:
      - name: npm-cache
        path: /root/.npm
  - name: Node Lint
    image: node:12-slim
    commands:
      - npm run lint
    depends_on:
      - Node Install
  - name: Node Audit
    image: node:12-slim
    commands:
      - npm audit --audit-level=moderate
    depends_on:
      - Node Install
  - name: Node Dist
    image: node:12-slim
    commands:
      - npm run build
    depends_on:
      - Node Install
      - Node Lint # Cause why bother if failed

  - name: Server Generate
    image: golang:1.14
    volumes:
    - name: go-cache
      path: /go
    commands:
      - go generate ./...
      - echo -n "box," >> .buildtags
      - go run github.com/swaggo/swag/cmd/swag init -o pkg/swagdocs -g pkg/routes/api/api.go
      - echo -n "swagger," >> .buildtags
    when:
      branch: ['master']
    depends_on:
      - Node Dist

  - name: Server Test
    image: golang:1.14
    volumes:
    - name: go-cache
      path: /go
    commands:
      - go test -race ./...
      - go vet $(go list ./... | grep -v "vendor")
    depends_on:
      - Server Generate
  - name: Server Static Check
    image: golang:1.14
    volumes:
    - name: go-cache
      path: /go
    commands:
      - go run honnef.co/go/tools/cmd/staticcheck ./...
    depends_on:
      - Server Test
  - name: Server Build
    image: golang:1.14
    volumes:
    - name: go-cache
      path: /go
    commands:
      - echo -n "prometheus" >> .buildtags
      - go build -tags $(cat .buildtags) -o simple-auth-server simple-auth/cmd/server
    depends_on:
      - Server Generate
      - Node Dist
  - name: CLI Build
    image: golang:1.14
    volumes:
    - name: go-cache
      path: /go
    commands:
      - go build -tags boxconfig -o simple-auth-cli simple-auth/cmd/cli
    depends_on:
      - Server Generate

  - name: Integration Tests
    image: node:12-buster
    commands:
      - ./tests/quicktest.sh --nobuild
    depends_on:
      - Server Build

  - name: Docker Build
    image: docker:19
    volumes:
    - name: docker-socket
      path: /var/run/docker.sock
    commands:
      - docker build -t ${DRONE_REPO_NAME} -f Dockerfile.drone .
    when:
      branch: ['master']
    depends_on:
      - Server Build
      - CLI Build

volumes:
  - name: docker-socket
    host:
      path: /var/run/docker.sock
  - name: go-cache
    host:
      path: /var/ci/cache/simple-auth-go
  - name: npm-cache
    host:
      path: /var/ci/cache/simple-auth-npm

---
kind: pipeline
type: docker
name: Documentation

steps:
  - name: Node Install
    image: node:12-slim
    commands:
      - cd docs && npm ci
    volumes:
      - name: npm-cache
        path: /root/.npm
  - name: Docs Build
    image: node:12-slim
    commands:
      - cd docs && npm run build
  - name: Deploy
    image: node:12-slim
    environment:
      SURGE_LOGIN:
        from_secret: surge_login
      SURGE_TOKEN:
        from_secret: surge_token
    commands:
      - cd docs && npm run deploy
    when:
      branch: ['master']

volumes:
  - name: npm-cache
    host:
      path: /var/ci/cache/simple-auth-npm