version: '3.3'
services:
  simpleauth:
    build: ../../../
    ports:
      - 8082:80
    environment:
      SA_WEB_LOGIN_COOKIE_JWT_SIGNINGKEY: ra9etioahtjkj2345 # REPLACE THIS WITH SOMETHING UNIQUE!!!!
    volumes:
      - sadb:/var/lib/simple-auth

volumes:
  sadb: {}