version: '3.3'
services:
  nginx:
    #image: nginx:latest
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports: 
      - "8082:80"
    environment:
      NGINX_PORT: 80
  simpleauth:
    build: ../
    environment:
      SA_WEB_LOGIN_COOKIE_JWT_SIGNINGKEY: ra9etioahtjkj234
      SA_VERBOSE: 'true'
      SA_STATICFROMDISK: 'true'
      SA_WEB_HOST: "0.0.0.0:80"
