version: '3.3'
services:
  simpleauth:
    image: zix99/simple-auth:latest
    ports:
      - 8082:80
    environment:
      SA_WEB_LOGIN_COOKIE_JWT_SIGNINGKEY: a-unqiue-signing-key # REPLACE THIS WITH SOMETHING UNIQUE!!!!
      #region myconfig
      SA_DB_DRIVER: mysql
      SA_DB_URL: "sa:test@(db)/simpleauth?charset=utf8&parseTime=True&loc=Local"
      #endregion myconfig
    restart: always
    depends_on:
      - db
  db:
    image: mariadb:10.5
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_USER: sa
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: simpleauth
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: {}
