version: '3.3'
services:
  nginx:
    image: nginx:latest
  simpleauth:
    build: ../../
    ports:
      - 8082:80
    environment:
      SA_WEB_LOGIN_COOKIE_JWT_SIGNINGKEY: ra9etioahtjkj2345
      SA_VERBOSE: 'true'
      SA_WEB_LOGIN_SETTINGS_ROUTEONLOGIN: "/"
      SA_WEB_GATEWAY_ENABLED: 'true'
      SA_WEB_GATEWAY_TARGETS: 'http://nginx'
    volumes:
      - sadb:/var/lib/simple-auth

volumes:
  sadb: {}